language: python
python:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34

install:
  - pip install .
  - pip install -r test_requirements.txt
  - pip install -r requirements.txt

script: tox -e $TOX_ENV
