language: python
python:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34

install:
  - pip install tox
  - pip install .
  - pip install -r test_requirements.txt
  - pip install -r requirements.txt

script: tox
